import type { Metadata } from "next";
import "./globals.css";
import { BalanceProvider } from "@/context/balanceContext/BalanceContext";

export const metadata: Metadata = {
  title: "Example Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BalanceProvider>
        {children}
        </BalanceProvider>
      </body>
    </html>
  );
}